#!/bin/sh
      ### BEGIN INIT INFO
# Provides:          fbgroupbackuphttpd
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Facebook group backup HTTP server
# Description:       Start/stop Facebook group backup HTTP server on port 9999
### END INIT INFO
#copy this file to /etc/init.d/
DESC="Facebook group backup HTTP server"
NAME=fbgroupbackuphttpd
#DAEMON=
# Start the service MAT
start() {
        /media/a8510270-6ecd-4eba-g8482-b16ee4af414a/NikiKiri/fbgroupbackup.sh startserver
        echo
}
# Restart the service MAT
stop() {
        kill $(netstat -tulpn 2>/dev/null | grep 0.0.0.0:9999 | grep -oE [0-9]+/python | grep -oE [0-9]+)
        echo
}
status() {
      if netstat -tulpn 2>/dev/null | grep 0.0.0.0:9999; then
            exit_var=3
            echo "Service is not running"
      else
            exit_var=0
            echo "Service is running"
      fi
}
### main logic ###
exit_var=0
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit $exit_var